### ISSUE TITLE
Integrate Reverse IP to DNS (Hacker Target) and an ARIN Lookup

### ISSUE THREAD

**Issue by Xboarder56** [mitchmoser/sputnik#11]
The lookup URL for Hacker Target reverse IP is https://api.hackertarget.com/reverseiplookup/?q=%IP%

The lookup URL for mxtoolbox ARIN is http://www.mxtoolbox.com/SuperTool.aspx?action=arin%3a%IP%

Note: the %IP% placeholder is for the IP address.

**Comment by mitchmoser** [comment]
Closing referencing Pull Request #12 Added MxToolbox ARIN lookup and HackerTarget Reverse IP Lookup
