### ISSUE TITLE
What license is this repo under?

### ISSUE THREAD

**Issue by tsuggs** [mitchmoser/sputnik#2]
On the Firefox addon store page, the license is listed as Mozilla Public License 2.0, but I did not see a license referred to in the repository here on github. Is the Chrome addon's source code MPL 2.0 as well? It may be useful to add a license.md for clarification.

Hope all is treating you well, and thank you for sharing this most useful tool! :)

**Comment by mitchmoser** [comment]
Thank you for the suggestion. I've added `LICENSE.md` - a local copy of the Mozilla Public License, Version 2.0.
