### ISSUE TITLE
Add URLhaus

### ISSUE THREAD

**Issue by jamesdeluk** [mitchmoser/sputnik#25]
https://urlhaus.abuse.ch/

https://urlhaus.abuse.ch/browse.php?search=[search-term]

Does hashes, URLs, domains, IPs.

**Comment by jamesdeluk** [comment]
OK, I think I've done it: https://github.com/mitchmoser/sputnik/pull/26

**Comment by mitchmoser** [comment]
Thank you for the contribution!
Accepted #26 
Closing issue
