### ISSUE TITLE
Request: Changelog for Firefox extension

### ISSUE THREAD

**Issue by geeknik** [mitchmoser/sputnik#8]
Is it possible to get a changelog for the Firefox extension? Currently when updating there is no information visible:

![screenshot_2019-01-19_13-27-58](https://user-images.githubusercontent.com/466878/51431427-3eb92c00-1bee-11e9-99e8-b6dceb7bf736.png)

Thank you in advance and thank you for a super useful browser extension!

**Comment by mitchmoser** [comment]
Definitely! This one in particular was such a small adjustment from the previous update. I changed the name of a menu item from 'TOR Relay Search' to 'TOR Relay'... at the end of the day, these are all searches, right? Anyway, looking back over my release notes, this seems like an exception to the rule. I usually include release notes and I will definitely continue to do so! Thanks for the feedback
